config/routes.rb
Rails.application.routes.draw do
  
  root 'finder#index'
  
  get 'alphabetized' => 'finder#alphabetized'
  get 'missing_email' => 'finder#missing_email'
  resources :customers

  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :full_name, presence: true
  validates :phone_number, presence: true
  validates :image, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:full_name, :phone_number, :email_address, :image, :notes)
    end
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  #finds all customers
  def index
    @customers = Customer.all
  end
  #sorts customers alphabetically
  def alphabetized
    @customers = Customer.order(:full_name)
  end
  # finds all customers with no email address
  # couldn't figure out why no customers were showing for this
  # should be showing 2 customers :(
  def missing_email
    @customers = Customer.where(:email_address => nil)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.erb

<table>
    <thead>
      <tr>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
      </tr>
      <tr>
        <th><%= customer.full_name %></th>
        <th colspan="1"></th>
      </tr>
    </thead>
  
    <tbody>
        <tr>
          <td><%= image_tag customer.image, size: "160x180" %></td>
        </tr>
        <tr>
          <td><div>Phone:</div> <%= customer.phone_number %></td>
        </tr>
        <tr>
          <td><div>Email:</div> <%= customer.email_address %></td>
        </tr>
        <tr>
          <td><div>Notes:</div> <%= customer.notes %></td>
        </tr>
  
    </tbody>
  
  

</table>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>All Customers</h1>

<p><%= link_to 'New Customer', new_customer_path %> -
<%= link_to 'Destroy', @customer, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<%= render @customers %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @customer.full_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @customer.phone_number %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @customer.email_address %>
</p>

<p>
  <strong>Image:</strong>
  <%= @customer.image %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @customer.notes %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/finder/alphabetized.html.erb
<h1>All Customers Alphebetized!:</h1>

<%=render @customers %>

app/views/finder/index.html.erb
<h1>All Customers:</h1>
<p><%= link_to 'New Customer', new_customer_path %> -
<%= link_to 'Missing Emails', missing_email_path %>
</p>
<%=render @customers %>

app/views/finder/missing_email.html.erb
<h1>All Customers Missing Emails:</h1>
<p><%= link_to 'New Customer', new_customer_path %> -
<%= link_to 'Index Page', root_path %>
</p>
<% render @customers %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ultimate Challenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>